[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_flags = 
    -Wno-return-type
    -Wno-strict-aliasing
    -fpermissive
lib_deps =
    adafruit/DHT sensor library @ ^1.4.4
    adafruit/Adafruit Unified Sensor @ ^1.1.9
    eloquentarduino/EloquentTinyML @ ^0.0.3